export const FETCH_SHEEPS_START = "FETCH_SHEEPS_START";
export const FETCH_SHEEPS_SUCCESS = "FETCH_SHEEPS_SUCCESS";

export const START_NEW_SHEEP = "START_NEW_SHEEP";
export const SAVE_NEW_SHEEP_SUCCESS = "SAVE_NEW_SHEEP_SUCCESS";

export const START_EDIT_SHEEP = "START_EDIT_SHEEP";
export const EDIT_SHEEP_SUCCESS = "EDIT_SHEEP_SUCCESS";
export const FETCH_SHEEP = "FETCH_SHEEP";